// <auto-generated />
using System;
using ElectionManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElectionManagement.Migrations
{
    [DbContext(typeof(ElectionDbContext))]
    [Migration("20260306133515_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ElectionManagement.Models.ElectionProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gio11")
                        .HasColumnType("int");

                    b.Property<int>("Gio14")
                        .HasColumnType("int");

                    b.Property<int>("Gio16")
                        .HasColumnType("int");

                    b.Property<int>("Gio19")
                        .HasColumnType("int");

                    b.Property<int>("Gio7")
                        .HasColumnType("int");

                    b.Property<int>("Gio9")
                        .HasColumnType("int");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenKhuVuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TongCuTri")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Stt", "TenKhuVuc")
                        .IsUnique()
                        .HasFilter("[TenKhuVuc] IS NOT NULL");

                    b.ToTable("ElectionProgresses");
                });

            modelBuilder.Entity("ElectionManagement.Models.ElectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("KhuVuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhieuHopLe")
                        .HasColumnType("int");

                    b.Property<int>("PhieuKhongHopLe")
                        .HasColumnType("int");

                    b.Property<int>("PhieuPhatRa")
                        .HasColumnType("int");

                    b.Property<int>("PhieuThuVe")
                        .HasColumnType("int");

                    b.Property<int>("Stt")
                        .HasColumnType("int");

                    b.Property<int>("TongCuTri")
                        .HasColumnType("int");

                    b.Property<int>("UngCuVien1")
                        .HasColumnType("int");

                    b.Property<int>("UngCuVien2")
                        .HasColumnType("int");

                    b.Property<int>("UngCuVien3")
                        .HasColumnType("int");

                    b.Property<int>("UngCuVien4")
                        .HasColumnType("int");

                    b.Property<int>("UngCuVien5")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Stt")
                        .IsUnique();

                    b.ToTable("ElectionResults");
                });

            modelBuilder.Entity("ElectionManagement.Models.ImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("int");

                    b.Property<string>("Errors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuccessRows")
                        .HasColumnType("int");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImportLogs");
                });

            modelBuilder.Entity("ElectionManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
