// <auto-generated />
using System;
using ElectionManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElectionManagement.Migrations
{
    [DbContext(typeof(ElectionDbContext))]
    [Migration("20260312045948_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ElectionManagement.Models.BallotVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallotType1Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallotType1Votes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallotType2Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallotType2Votes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallotType3Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallotType3Votes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Candidate1Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Candidate1Votes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Candidate2Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Candidate2Votes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Candidate3Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Candidate3Votes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Candidate4Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Candidate4Votes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Candidate5Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Candidate5Votes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Candidate6Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Candidate6Votes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Candidate7Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Candidate7Votes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistrictName")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvalidBallots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssuedBallots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceivedBallots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCandidates")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidBallots")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BallotVerifications");
                });

            modelBuilder.Entity("ElectionManagement.Models.ElectionProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonVi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gio10")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gio12")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gio14")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gio16")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gio19")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gio8")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenKhuVuc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TiLe")
                        .HasColumnType("TEXT");

                    b.Property<int>("TongCuTri")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TongCuTriDiBau")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Stt", "TenKhuVuc")
                        .IsUnique();

                    b.ToTable("ElectionProgresses");
                });

            modelBuilder.Entity("ElectionManagement.Models.ElectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KhuVuc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhieuHopLe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhieuKhongHopLe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhieuPhatRa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhieuThuVe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.Property<int>("TongCuTri")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UngCuVien1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UngCuVien2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UngCuVien3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UngCuVien4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UngCuVien5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UngCuVien6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UngCuVien7")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UngCuVien8")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ElectionResults");
                });

            modelBuilder.Entity("ElectionManagement.Models.ImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Errors")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuccessRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportLogs");
                });

            modelBuilder.Entity("ElectionManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
